apiVersion: v1
kind: Pod
metadata:
  name: cpu-limit
  namespace: bsegitim
spec:
  containers:
  - name: cpu-limit-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
