apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: bsegitim
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-pvtypo 
          mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: grafana-pvtypo
        persistentVolumeClaim:
          claimName: grafana-pvtypo
