apiVersion: v1
kind: Service
metadata: 
  name: grafana-nodeport
  namespace: bsegitim
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: tcp
  selector:
    app: grafana
